project_id = "wdrrwzddhcnnbjrzscvo"

[functions.solve-quiz]
verify_jwt = false

[functions.generate-presentation]
verify_jwt = false

[functions.generate-assignment]
verify_jwt = false

[functions.generate-images]
verify_jwt = false

[functions.generate-exam]
verify_jwt = false
